---
- hosts: localhost
  become: yes
  tasks:
  - name: Install a list packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

  - name: download
    shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -'

  - name: add repository
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'
  
  - name: Upgrade all packages to the latest version
    shell: 'apt-get update -y'
    
  - name: install docker
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli
  
  - name: add repository
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'

  - name: add service 
    shell: 'mkdir -p /etc/systemd/system/docker.service.d'
  
  - name: restart service
    shell: 'systemctl daemon-reload && systemctl restart docker'

  - name: permission to current user
    shell: 'sudo usermod -aG docker $USER'
