---
- hosts: localhost
  become: yes
  tasks:
  - name: Install a list packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

  - name: download
    shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -'

  - name: add repository
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'
  
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: install docker
    apt: 
      name: 'docker-ce=18.06.3~ce~3-0~debian'
